name: Code test + deploy to preview

on:
  push:
    branches-ignore:
      - master
    # paths:
    #   - "src/**/*.tsx"
    #   - "src/**/*.ts"
    #   - "cypress/**/*.ts"

jobs:

  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          PRODUCTION: false
          GITHUB_DEPLOYMENT_ENV: "Preview"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          